/* this code was generated by automated tool,
   should not edit by hand */

export interface Token {
  GenerateToken(request: GenerateTokenRequest): Promise<GenerateTokenResponse>;
  ValidateToken(request: ValidateTokenRequest): Promise<BoolResult>;
  RevokeToken(request: RevokeTokenRequest): Promise<BoolResult>;
}

export interface BoolResult {
  result?: boolean;
}

export interface GenerateTokenRequest {
  sub?: string;
}

export interface GenerateTokenResponse {
  token?: string;
}

export interface ValidateTokenRequest {
  token?: string;
}

export interface RevokeTokenRequest {
  token?: string;
}
